baseurl = "/"
title = "My blog"
theme = "ghostwriter-master"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "deion.menor"
    description = "a collection of random words, thoughts, and data points"
    github = "https://github.com/deionmenor"
    twitter = "https://twitter.com/deenulatr"
    email = "deionmenor@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"