

baseURL = "https://example.com"
languageCode = "en-us"
title = "Deion Menor"
theme = "hugo-theme-noteworthy-master"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 5 # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "UA-164359515-1" 

# Add your Disqus shortname here.
disqusShortname = ""    

[taxonomies]
  tag = "tags"

[author]
	name = "deionmenor"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "this blog is a work in progress. much like the author"

    showReadMore = false

    # Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
    enableKofi = false
    kofi = ""

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
	email = "deionmenor@gmail.com"
    twitter = "twitter.com/hopelessfanatik"
	linkedin = "linkedin.com/deionmenor"
    github = "github.com/deionmenor"

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1


# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true